"""create initial schema

Revision ID: e5985d70e6e4
Revises: 
Create Date: 2026-07-03 16:27:51.269072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5985d70e6e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('yarns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=False),
    sa.Column('fiber_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('needle_min_mm', sa.Float(), nullable=True),
    sa.Column('needle_max_mm', sa.Float(), nullable=True),
    sa.Column('ball_weight_grams', sa.Integer(), nullable=True),
    sa.Column('ball_length_meters', sa.Integer(), nullable=True),
    sa.Column('gauge_stitches', sa.Integer(), nullable=False),
    sa.Column('gauge_rows', sa.Integer(), nullable=False),
    sa.Column('care_machine_washable', sa.Boolean(), nullable=False),
    sa.Column('care_wash_temperature_celsius', sa.Integer(), nullable=True),
    sa.Column('care_wash_program', sa.String(length=100), nullable=True),
    sa.Column('care_bleach_allowed', sa.Boolean(), nullable=False),
    sa.Column('care_tumble_dry_allowed', sa.Boolean(), nullable=False),
    sa.Column('care_dry_clean_allowed', sa.Boolean(), nullable=False),
    sa.Column('care_dry_flat', sa.Boolean(), nullable=False),
    sa.Column('care_max_iron_temperature_celsius', sa.Integer(), nullable=True),
    sa.Column('crochet_hook_size_mm', sa.Float(), nullable=True),
    sa.Column('balls_per_garment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yarns')
    op.drop_table('users')
    op.drop_table('invitations')
    op.drop_table('brands')
    # ### end Alembic commands ###
